datadir: ~/workspace/pn/visitlocal
zappsdir: ../
wallet:
  keystore_path: ~/workspace/pn/visitlocal/keystore
mode: zappdev
log:
  sendLogs: false
  level: debug
storage:
  arweave_host: localhost
  arweave_protocol: http
  arweave_port: 1984
  use_arweave_bundler: false
  use_arlocal: true
  arweave_gateway_url: http://localhost:1984/graphql
network:
  web3:
    xnet:
      type: "eth"
      name: "Xnet"
      http_address: "localhost:7545"
      ws_address: "localhost:7545"
      currency_name: "xPoint"
      currency_code: "xPOINT"
      tls: false
      gas_price_wei: 610158337
      tokens: []
    rinkeby:
      type: "eth"
      name: "Rinkeby"
      http_address: "rinkeby.infura.io/v3/90b29027d7a346bd951a7569bf598474" # TODO: project ID
      ws_address: "rinkeby.infura.io/v3/90b29027d7a346bd951a7569bf598474" # TODO: project ID
      currency_name: "rinkebyEth"
      currency_code: "rinkebyETH"
      eth_tld_resolver: "0xf6305c19e814d2a75429Fd637d01F7ee0E77d615"
      tls: true
api:
  address: 127.0.0.1
  port: 24682
zproxy:
  host: 127.0.0.1
  port: 65502
  server_port: 8779
  server_http_port: 8780