version: '3.9'

services:
  point_node:
    extends:
      file: docker-compose.yaml
      service: point_node
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - point_contracts_znet:/app/truffle/build/contracts
      - point_node_data_znet:/data
    environment:
      - BLOCKCHAIN_URL=https://znet.pointspace.io
      - CONTRACT_ADDRESS_MIGRATIONS=0xbE2a4E61eEDcE7102EA37B3AE0D741A50fC3ce4d
      - CONTRACT_ADDRESS_IDENTITY=0x4BeF84Ebf41Ac28ab9A46d94906ed1793dF2952E
      - CONTRACT_ADDRESS_STORAGE_PROVIDER_REGISTRY=0x8A2AB2cd8cb980e80b43BE4E62fdd90Cb6e44029
      - ARWEAVE_EXPERIMENT_VERSION_MINOR=8

  database:
    extends:
      file: docker-compose.yaml
      service: database
    volumes:
      - database_data_znet:/var/lib/postgresql/data/

volumes:
  point_contracts_znet:
  point_node_data_znet:
  database_data_znet:
