version: '3.9'

services:
  blockchain_node:
    image: neonlabsorg/solana:${BLOCKCHAIN_VERSION:-v1.7.9-resources}
    container_name: pointnetwork_blockchain_node
    hostname: blockchain_node
    healthcheck:
      test: solana cluster-version
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      SOLANA_URL: http://blockchain_node:8899
      RUST_LOG: |
        solana_runtime::system_instruction_processor=warn,solana_runtime::message_processor=debug,solana_bpf_loader=debug,solana_rbpf=debug
    volumes:
      - blockchain_node_data:/opt/solana/config:rw

  blockchain_provider:
    image: neonlabsorg/proxy:${BLOCKCHAIN_PROVIDER_VERSION:-stable}
    container_name: pointnetwork_blockchain_provider
    healthcheck:
      test: |
        curl -X POST \
          -H 'Content-Type: application/json' \
          -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":0}' \
          http://localhost:9090/solana
      interval: 60s
      timeout: 5s
      retries: 4
      start_period: 30s
    ports:
      - 127.0.0.1:9090:9090
    environment:
      CONFIG: ci
      SOLANA_URL: http://blockchain_node:8899
    volumes:
      - blockchain_provider_env:/opt/env:rw
      - blockchain_provider_config:/root/.config/solana:rw
      - ./scripts/handle-neon-proxy.sh:/opt/proxy/handle-run-proxy.sh:ro
    entrypoint: /opt/proxy/handle-run-proxy.sh

  contract_deployer:
    image: pointnetwork/pointnetwork_deployer:${POINT_DEPLOYER_VERSION:-neon_proxy-0.0.1}
    container_name: pointnetwork_contract_deployer
    restart: 'no'
    volumes:
      - ./geth/keystore:/.keystore
      - ./truffle/migrations:/truffle/migrations:ro
      - ./truffle/contracts:/truffle/contracts:ro
      - ./truffle/truffle-config-neon.js:/truffle/truffle-config.js:ro
      - ./geth/keystore:/.keystore:ro
      - point_contracts:/build:rw
    command: deploy --network znet
    environment:
      - DEPLOYER_COMPILER_VERSION=native
      - BLOCKCHAIN_NETWORK_ID=*
      - DEPLOYER_BUILD_PATH=/build
      - DEPLOYER_ENV=znet
      - BLOCKCHAIN_URL=http://blockchain_provider:9090/solana

volumes:
  point_contracts:
  blockchain_node_data:
  blockchain_provider_env:
  blockchain_provider_config:
