version: '3.9'

services:
  gateway:
    extends:
      file: docker-compose.storage.yaml
      service: gateway
    depends_on:
      gateway_db:
        condition: service_healthy

    volumes:
      - gateway_data_ar:/app
    environment:
      ARWEAVE_NODES: '["http://0.0.0.0:1984/"]'

  gateway_db:
    extends:
      file: docker-compose.storage.yaml
      service: gateway_db
    volumes:
      - gateway_db_data_ar:/var/lib/postgresql/data

volumes:
  gateway_data_ar:
  gateway_db_data_ar:
