version: '3.2'

services:
  curator:
    build:
      context: extensions/curator/
    init: true
    volumes:
      - ./extensions/curator/config/curator.yml:/usr/share/curator/config/curator.yml:ro,Z
      - ./extensions/curator/config/delete_log_files_curator.yml:/usr/share/curator/config/delete_log_files_curator.yml:ro,Z
      # (!) CA certificate. Generate using instructions from tls/README.md.
      - ./tls/kibana/elasticsearch-ca.pem:/usr/share/curator/config/elasticsearch-ca.pem:ro,z
    networks:
      - elk
    depends_on:
      - elasticsearch
