mode: test
deployer_account: 011967d88c6b79116bb879d4c2bc2c3caa23569edd85dfe0bc596846837bbc8e
log:
  level: error
  sendLogs: false
api:
  csrf_enabled: false
network:
  default_network: "mock_eth_net"
  web3:
    mock_eth_net:
      identity_contract_id: ""
      identity_contract_address: ""
      type: eth
    mock_sol_net:
      type: solana
