storage:
  arweave_experiment_version_major: 123
  arweave_experiment_version_minor: 456
  arweave_bundler_url: http://127.0.0.1:80
  arweave_gateway_url: http://127.0.0.1:3000/graphql
  arweave_host: 127.0.0.1
  arweave_protocol: http
  arweave_port: 1984
network:
  web3:
    ynet: http://127.0.0.1:7545
api:
  address: 0.0.0.0
zproxy:
  host: 0.0.0.0
log:
  level: debug

