mode: test
deployer_account: 011967d88c6b79116bb879d4c2bc2c3caa23569edd85dfe0bc596846837bbc8e
log:
  level: error
  sendLogs: false
api:
  csrf_enabled: false
network:
  default_network: "xnet"
  identity_contract_address: "0x8E34Fc67034b8A593E87d5f2644D098A3dBd2Fe7"
