# Curator configuration
# https://www.elastic.co/guide/en/elasticsearch/client/curator/current/configfile.html

client:
  hosts:
    - elasticsearch
  port: 9200
  http_auth: 'elastic:changeme'
  use_ssl: True
  certificate: /usr/share/curator/config/elasticsearch-ca.pem

logging:
  loglevel: INFO
  logformat: default
