#!/bin/bash

# This script is used to deploy a zapp from any location external to the Docker image.

POINTNETWORK_DEPLOYSPACE="$HOME/.point/src/deployspace"

# Delete everything in deployspace first (keeping the README file)
mv $POINTNETWORK_DEPLOYSPACE/README.md /tmp/.
rm -r $POINTNETWORK_DEPLOYSPACE/*
mv /tmp/README.md $POINTNETWORK_DEPLOYSPACE/.

# Copy current Zapp folder to deployspace
cp -r * $POINTNETWORK_DEPLOYSPACE

# Execute the deployspace script from inside the website owner container
docker exec -it pointnetwork_website_owner /app/scripts/deploy-from-deployspace.sh