#!/bin/bash

# This script is used to deploy a zapp from any location external to the Docker image.

POINTNETWORK_DEPLOYSPACE="$HOME/.point/src/pointnetwork/deployspace"

# Validate current directory contains both point.deploy.json and routes.json files and a public folder
[ ! -f point.deploy.json ] && { echo "point.deploy.json file does not exist. Aborting deployment."; exit 1; }
[ ! -f routes.json ] && { echo "routes.json file does not exist. Aborting deployment."; exit 1; }
[ ! -d ./public ] && { echo "./public folder does not exist. Aborting deployment."; exit 1; }

# Create the deployspace folder if it does not exist on the host
[ ! -d $POINTNETWORK_DEPLOYSPACE ] && { echo "Creating $POINTNETWORK_DEPLOYSPACE"; mkdir $POINTNETWORK_DEPLOYSPACE; }

echo
echo "Copying Zapp files to Point Node deployspace...(please wait)"
echo

# Ensure the deployspace folder is empty
[ "$(ls -A $POINTNETWORK_DEPLOYSPACE/)" ] && rm -r $POINTNETWORK_DEPLOYSPACE/*

# Copy current Zapp folder to deployspace
cp -r * $POINTNETWORK_DEPLOYSPACE

# Execute the deployspace script from inside the website owner container
docker exec -it pointnetwork_website_owner /app/scripts/deploy-from-deployspace.sh

# Finally, clean up and delete everything in deployspace
rm -r $POINTNETWORK_DEPLOYSPACE/*