/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Identity__factory } from "./Identity__factory";
export { PointSocial__factory } from "./PointSocial__factory";
