#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm exec lint-staged
npm exec --prefix ./internal/explorer.point lint-staged
# this is failing - will be re-enabled after merging my react refactoring PR
#cd internal/explorer.point && npm run fix
npm exec tsc
